config:
  appEnv: "uat"
  redisAddr: "51.79.85.92:6379"
  redisSentinels: "51.79.85.92:26379,51.79.85.92:26380,51.79.85.92:26381"
  redisSentinelMaster: "amss-master"
  prometheusEnabled: "true"
  corsAllowedOrigins: "https://amss.leoulgirma.com,https://amss-api-uat.duckdns.org,http://51.79.85.92:5173,http://localhost:5173"

image:
  server:
    tag: latest
  worker:
    tag: latest

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: amss-api-uat.duckdns.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: amss-uat-tls
      hosts:
        - amss-api-uat.duckdns.org

server:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

worker:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
