config:
  appEnv: "uat"
  redisAddr: "51.79.85.92:6379"
  prometheusEnabled: "true"

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: amss-api-uat.duckdns.org
      paths:
        - path: /
          pathType: Prefix
