apiVersion: v1
kind: Secret
metadata:
  name: {{ include "amss.fullname" . }}-secret
  labels:
{{ include "amss.labels" . | indent 4 }}
type: Opaque
stringData:
  DB_URL: {{ .Values.secrets.dbUrl | quote }}
  JWT_PRIVATE_KEY_PEM: {{ .Values.secrets.jwtPrivateKeyPem | quote }}
  JWT_PUBLIC_KEY_PEM: {{ .Values.secrets.jwtPublicKeyPem | quote }}
