apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "amss.fullname" . }}-server
  labels:
{{ include "amss.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
{{ include "amss.selectorLabels" . | indent 6 }}
      component: server
  template:
    metadata:
      labels:
{{ include "amss.selectorLabels" . | indent 8 }}
        component: server
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
{{- end }}
      containers:
        - name: server
          image: "{{ .Values.image.server.repository }}:{{ default .Chart.AppVersion .Values.image.server.tag }}"
          imagePullPolicy: {{ .Values.image.server.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
          resources:
{{ toYaml .Values.server.resources | indent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "amss.fullname" . }}-config
            - secretRef:
                name: {{ include "amss.fullname" . }}-secret
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
